version: '3'
   
services:

  db:
    container_name: mysqlD
    image: mysql:5.7
    restart: always
    ports:
      - 33060:3306
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: prueba
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql:/var/lib/mysql-files

  web:
    build: .
    restart: always
    container_name: pythonD
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      
      
  
  

